spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/livros}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update